dataset:
    dataset_root_path: "/home/islab-ai/dataset/mapilary_vista/vistas"
    batch_size: 48
    num_workers: 1
    ignore_index: null
seg_model:
    name: "mask2former_vistas"
    #name: "wideresnet38_deeplab3_vistas"

encoder_model:
    name: "resnet50"
    type: "conv"
    n_trainable_layers: 1

training:
    epochs: 110
    eps: 0.01
    mask_temperature: 0.10
    weight_decay: 0.0001
    grad_clip: 1.0
    decoder_hidden_channels: 64
    pruning:
        dense_warmup_epochs: 4
        pruning_epochs: 2
        mask_temperature_start: 1.0
        mask_temperature_end: 0.10
        dense_stealth_factor: 0.0

    loss_weight:
        l_atk: 1.0
        l_keep: 0.1
        l_sem: 0.1
        l_stealth: 0.2
        l_budget: 0.01

        kappa: 0.0
        rho: 0.5

        importance_attack: 0.6
        importance_semantic: 0.4
        importance_visibility: 0.25

        stealth_gradient: 0.2
    scheduler:
        lr: 0.001
        warmup_epochs: 3
        warmup_start_factor: 0.1
        min_lr: 0.0001

export:
    log_mode: "overwrite"
    save_dir: "results/adversarial_seg"
    checkpoint_interval: 5