dataset:
    dataset_root_path: "/home/islab-ai/dataset/mapilary_vista/vistas"
    batch_size: 48
    num_workers: 1
seg_model:
    name: "segformer_b0_ade"
encoder_model:
    name: "resnet50"
    type: "conv"
    n_trainable_layers: 1
patch_model:
    ckpt_path: "results/adversarial_seg/20260907_101349/model/model.pt"
    eps: 0.10
export:
    save_dir: 'results/adversarial_seg'
    checkpoint_interval: 5