dataset:
    dataset_root_path: "/home/islab-ai/dataset/mapilary_vista/vistas"
    batch_size: 48
    num_workers: 1
    ignore_index: null
seg_model:
    name: "mask2former_vistas"
encoder_model:
    name: "resnet50"
    type: "conv"
    n_trainable_layers: 1
patch_model:
    ckpt_path: "results/adversarial_seg/20260908_131237/model/model.pt"
    mask_temperature: 0.10
    eps: 0.03
    selection_grid: 64
export:
    save_dir: 'results/adversarial_seg'
    checkpoint_interval: 5